### ISSUE TITLE
Make images-base-path in application.yml configurable for development

### ISSUE THREAD

**Issue by nck974** [nck974/diogenes#116]
The property has to be set in development to:

```yaml
file:
  # Location in file system:
  uploads-dir: ./uploads
  images-dir: files/items/images
  # API Endpoint path
  images-base-path: http://localhost:8080${server.servlet.context-path}/api/v1/files/images/
```

Create a property for the base url `http://localhost:8080`
